<?xml version="1.0"?>
<robot name="differential_wheeled_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find mastering_ros_robot_description_pkg)/urdf/diff_wheeled_base.xacro" /> 
  <xacro:include filename="$(find mastering_ros_robot_description_pkg)/urdf/sensors/hokuyo_laser.xacro" /> 

	<gazebo>
  	<plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
	    <legacyMode>true</legacyMode>
	    <rosDebugLevel>Debug</rosDebugLevel>
	    <publishWheelTF>false</publishWheelTF>
	    <robotNamespace>/diff_wheeled</robotNamespace>
	    <publishTf>1</publishTf>
	    <publishWheelJointState>true</publishWheelJointState>
	    <alwaysOn>true</alwaysOn>
	    <updateRate>100.0</updateRate>
	    <leftJoint>front_left_wheel_joint</leftJoint>
	    <rightJoint>front_right_wheel_joint</rightJoint>
	    <wheelSeparation>${2*base_radius}</wheelSeparation>
	    <wheelDiameter>${2*wheel_radius}</wheelDiameter>
	    <broadcastTF>1</broadcastTF>
	    <wheelTorque>30</wheelTorque>
	    <wheelAcceleration>1.8</wheelAcceleration>
	    <commandTopic>cmd_vel</commandTopic>
	    <odometryFrame>odom</odometryFrame> 
	    <odometryTopic>odom</odometryTopic> 
	    <robotBaseFrame>base_footprint</robotBaseFrame>
   </plugin>
  </gazebo> 
</robot>
