diff_wheeled: 
  # Publish all joint states ----------------------------------- 
  joint_state_controller: 
    type: joint_state_controller/JointStateController 
    publish_rate: 50
   
  # Position Controllers --------------------------------------- 
  diff_drive_controller: 
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'front_left_wheel_joint'
    right_wheel: 'front_right_wheel_joint'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 999999999.0  # 默认的指令timeout是0.5s, 设置为999999999.0, 使其不超时
    base_frame_id: 'base_footprint'
